### ISSUE TITLE
Real world fine tuning

### ISSUE THREAD

**Issue by Windson9** [NVIDIA-AI-IOT/robot_freespace_seg_Isaac_TAO#1]
![annotation](https://user-images.githubusercontent.com/37536581/174972081-5c052918-8ae9-4636-b0de-15962de97ec5.png)
Hello, I am following your tutorial and everything went well until Real world fine tune. I am not able to achieve ideal stats after training on real world data. Can you please upload the train labels and images for real world fine tune ? If not, can you please explain how you have done the annotation. I have assigned 'label 1' to the objects and the rest is 'label 0' (Reference image is attached). 

A little help would be great. Thanks!

**Comment by RishabhChadha-97** [comment]
Hello, sorry for the late reply. Unfortunately we cannot release the real world images with annotations. What do the metrics look like after training on synthetic data? (sim2sim followed by sim2real) Is the environment in the real world drastically different from the simulation scene? We had used the labelme tool for data annotation. Also, please verify that the annotated labels have only 2 classes (0 and 1)

**Comment by RishabhChadha-97** [comment]
closing the issue since no response
